# Generated by Django 5.0.6 on 2024-06-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
